//! Typed IPC: the tauri-specta builder and the generated TypeScript bindings.
//!
//! Regenerate `apps/desktop/src/lib/ipc/bindings.ts` with `pnpm gen:ipc` after changing a command
//! or an IPC type. CI fails if the committed file is out of date.

use tauri_specta::{Builder, collect_commands, collect_events};

use crate::{commands, logging};

/// Every command and event exposed to the UI.
pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::documents::open_document,
            commands::documents::close_document,
            commands::view::set_visible_pages,
            commands::content::get_outline,
            commands::content::get_page_text,
        ])
        .events(collect_events![logging::AppErrorEvent])
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    /// Writes the TypeScript bindings. Run via `pnpm gen:ipc`.
    #[test]
    fn export_bindings() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/lib/ipc/bindings.ts");
        super::builder()
            .export(
                Typescript::default().header("// Generated by tauri-specta. Do not edit; run `pnpm gen:ipc`.\n/* eslint-disable */"),
                path,
            )
            .expect("export TypeScript bindings");
    }
}
