// Generated by tauri-specta. Do not edit; run `pnpm gen:ipc`.
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Opens the PDF at `path`, adds it to the recent files and returns what the UI needs to show it. */
	openDocument: (path: string) => typedError<OpenedDocument, AppError>(__TAURI_INVOKE("open_document", { path })),
	/**  Closes a document and drops its cached tiles. */
	closeDocument: (docId: number) => typedError<null, AppError>(__TAURI_INVOKE("close_document", { docId })),
	/**
	 *  Tells the renderer which pages are mounted. Tiles already queued for other pages are skipped,
	 *  so fast scrolling doesn't leave a backlog of renders nobody will see.
	 */
	setVisiblePages: (docId: number, pages: number[]) => typedError<null, AppError>(__TAURI_INVOKE("set_visible_pages", { docId, pages })),
	/**  The document outline (bookmarks); empty when the document has none. */
	getOutline: (docId: number) => typedError<OutlineItem[], AppError>(__TAURI_INVOKE("get_outline", { docId })),
	/**  The text runs of one page with their positions, for the selectable text layer. */
	getPageText: (docId: number, page: number) => typedError<PageText, AppError>(__TAURI_INVOKE("get_page_text", { docId, page })),
	/**  The links on one page: areas that go to another page or to a URL. */
	getPageLinks: (docId: number, page: number) => typedError<PageLink[], AppError>(__TAURI_INVOKE("get_page_links", { docId, page })),
	/**  Opens a link from a document in the default browser or mail app. The UI asks the user first. */
	openExternalLink: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_external_link", { url })),
	/**  Recently opened files, newest first. Empty when the database is unavailable. */
	listRecentFiles: () => typedError<RecentEntry[], AppError>(__TAURI_INVOKE("list_recent_files")),
	/**  Takes a file off the recent list. */
	removeRecentFile: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_recent_file", { path })),
	/**  Remembers the page and zoom of an open document, to restore them next time. */
	saveView: (path: string, view: SavedView) => typedError<null, AppError>(__TAURI_INVOKE("save_view", { path, view })),
	/**
	 *  Starts searching a document for `query`, beginning at `start_page` and wrapping around.
	 *  Cancels the document's previous search. Results arrive as [`SearchProgressEvent`]s.
	 */
	startSearch: (docId: number, query: string, options: SearchOptions, startPage: number) => typedError<number, AppError>(__TAURI_INVOKE("start_search", { docId, query, options, startPage })),
	/**  Stops the document's running search, if any. */
	cancelSearch: (docId: number) => typedError<null, AppError>(__TAURI_INVOKE("cancel_search", { docId })),
};

/** Events */
export const events = {
	appErrorEvent: makeEvent<AppErrorEvent>("app-error-event"),
	searchProgressEvent: makeEvent<SearchProgressEvent>("search-progress-event"),
};

/* Types */
/**
 *  An error sent to the UI. The UI picks the user-facing message from `kind`; `detail` is technical
 *  and only for logs and bug reports.
 */
export type AppError = {
	/**  What went wrong. */
	kind: EngineErrorKind,
	/**  Technical detail. */
	detail: string,
};

/**  Sent to the UI when something failed unexpectedly (a caught panic). */
export type AppErrorEvent = {
	/**  Technical summary for the log; the UI shows its own friendly text. */
	detail: string,
};

/**  Facts about an open document. */
export type DocInfo = {
	/**  Number of pages. */
	pageCount: number,
	/**  The Info dictionary's Title, if any. */
	title: string | null,
	/**  The Info dictionary's Author, if any. */
	author: string | null,
	/**  True when the file is encrypted (with or without a user password). */
	isEncrypted: boolean,
	/**  True when the document has an AcroForm. */
	hasForms: boolean,
	/**  PDF version, e.g. "1.7". */
	pdfVersion: string,
};

/**  An open document as the UI sees it. */
export type DocSummary = {
	/**  Engine document id; used in commands and tile URLs. */
	id: number,
	/**  Full path of the file. */
	path: string,
	/**  File name for tabs and titles. */
	fileName: string,
	/**  Facts about the document. */
	info: DocInfo,
	/**  Display size of every page, in points. */
	pageSizes: PageSize[],
	/**  Current revision (part of every tile URL). */
	revision: number,
};

/**  A stable, serializable error code for the UI (which picks the user-facing message). */
export type EngineErrorKind = 
/**  See [`EngineError::LibraryLoad`]. */
"libraryLoad" | 
/**  See [`EngineError::FileNotFound`]. */
"fileNotFound" | 
/**  See [`EngineError::Io`]. */
"io" | 
/**  See [`EngineError::PasswordRequired`]. */
"passwordRequired" | 
/**  See [`EngineError::WrongPassword`]. */
"wrongPassword" | 
/**  See [`EngineError::Malformed`]. */
"malformed" | 
/**  See [`EngineError::UnsupportedSecurity`]. */
"unsupportedSecurity" | 
/**  See [`EngineError::UnknownDocument`]. */
"unknownDocument" | 
/**  See [`EngineError::PageOutOfRange`]. */
"pageOutOfRange" | 
/**  See [`EngineError::InvalidRequest`]. */
"invalidRequest" | 
/**  See [`EngineError::Render`]. */
"render" | 
/**  See [`EngineError::Cancelled`]. */
"cancelled" | 
/**  See [`EngineError::WorkerStopped`]. */
"workerStopped" | 
/**  See [`EngineError::Internal`]. */
"internal";

/**  Where a link goes. */
export type LinkTarget = 
/**  A page in this document. */
{ kind: "page"; 
/**  Target page. */
page: number } | 
/**  A web or mail address. Opened only after the user confirms. */
{ kind: "uri"; 
/**  The address. */
uri: string };

/**  An opened document and how it was last viewed. */
export type OpenedDocument = {
	/**  What the UI needs to show the document. */
	document: DocSummary,
	/**  The page and zoom it was left at (defaults for a file not opened before). */
	view: SavedView,
};

/**  An outline (bookmark) entry. */
export type OutlineItem = {
	/**  Entry title. */
	title: string,
	/**  Target page, if the entry points at one in this document. */
	page: number | null,
	/**  Nested entries. */
	children: OutlineItem[],
};

/**  A clickable link area on a page. */
export type PageLink = {
	/**  The clickable area. */
	rect: Rect,
	/**  Where it goes. */
	target: LinkTarget,
};

/**  A page's display size in PDF points (1/72 inch), with the page's /Rotate already applied. */
export type PageSize = {
	/**  Width as displayed. */
	widthPt: number | null,
	/**  Height as displayed. */
	heightPt: number | null,
};

/**  The text of one page, in reading order. */
export type PageText = {
	/**  Text runs; consecutive runs on different lines are separated by a line break when copied. */
	runs: TextRun[],
};

/**  A recent file and whether it is still there. */
export type RecentEntry = {
	/**  The file as last opened. */
	file: RecentFile,
	/**  False when the file has been moved or deleted since. */
	exists: boolean,
};

/**  A recently opened file. */
export type RecentFile = {
	/**  Full path, as last opened. */
	path: string,
	/**  File name for display. */
	fileName: string,
	/**  Pages when last opened. */
	pageCount: number,
	/**  When it was last opened, in milliseconds since the Unix epoch. */
	lastOpenedMs: number | null,
	/**  How it was last viewed. */
	view: SavedView,
};

/**  A rectangle in display points. */
export type Rect = {
	/**  Left edge. */
	x: number | null,
	/**  Top edge. */
	y: number | null,
	/**  Width. */
	width: number | null,
	/**  Height. */
	height: number | null,
};

/**  How a document was last viewed, restored when it is opened again. */
export type SavedView = {
	/**  Zero-based page the reader was on. */
	page: number,
	/**  Zoom factor (1 = 100%), if one was saved. */
	zoom: number | null,
	/**  Zoom mode ("custom", "fitWidth", "fitPage", "auto"), if one was saved. */
	zoomMode: string | null,
};

/**  One search match. */
export type SearchHit = {
	/**  The page the match is on. */
	page: number,
	/**  Highlight rectangles (one per line the match spans). */
	rects: Rect[],
	/**  Text around the match, for the results list. */
	snippet: string,
	/**  Where the match starts in `snippet`, in characters. */
	matchStart: number,
	/**  Length of the match in `snippet`, in characters. */
	matchLen: number,
};

/**  How to match a search query. */
export type SearchOptions = {
	/**  Match upper/lower case exactly. */
	matchCase: boolean,
	/**  Only match whole words. */
	wholeWord: boolean,
};

/**  A batch of search progress. */
export type SearchProgress = {
	/**  New matches since the previous report. */
	hits: SearchHit[],
	/**  Pages searched so far. */
	pagesSearched: number,
	/**  Pages in the document. */
	pageCount: number,
	/**  True on the last report (finished, cancelled, or the match limit was reached). */
	done: boolean,
	/**  True when the match limit cut the search short. */
	truncated: boolean,
};

/**  Progress of a running search: new matches since the previous event. */
export type SearchProgressEvent = {
	/**  The document searched. */
	docId: number,
	/**  The search this belongs to; events of older searches can arrive after a new one starts. */
	searchId: number,
	/**  Matches and counters. */
	progress: SearchProgress,
};

/**  A run of text on one line, as PDFium groups it. */
export type TextRun = {
	/**  The characters, in reading order. */
	text: string,
	/**  Where the run is drawn. */
	rect: Rect,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

