// Generated by tauri-specta. Do not edit; run `pnpm gen:ipc`.
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Opens the PDF at `path` and returns what the UI needs to show it. */
	openDocument: (path: string) => typedError<DocSummary, AppError>(__TAURI_INVOKE("open_document", { path })),
	/**  Closes a document and drops its cached tiles. */
	closeDocument: (docId: number) => typedError<null, AppError>(__TAURI_INVOKE("close_document", { docId })),
	/**
	 *  Tells the renderer which pages are mounted. Tiles already queued for other pages are skipped,
	 *  so fast scrolling doesn't leave a backlog of renders nobody will see.
	 */
	setVisiblePages: (docId: number, pages: number[]) => typedError<null, AppError>(__TAURI_INVOKE("set_visible_pages", { docId, pages })),
	/**  The document outline (bookmarks); empty when the document has none. */
	getOutline: (docId: number) => typedError<OutlineItem[], AppError>(__TAURI_INVOKE("get_outline", { docId })),
};

/** Events */
export const events = {
	appErrorEvent: makeEvent<AppErrorEvent>("app-error-event"),
};

/* Types */
/**
 *  An error sent to the UI. The UI picks the user-facing message from `kind`; `detail` is technical
 *  and only for logs and bug reports.
 */
export type AppError = {
	/**  What went wrong. */
	kind: EngineErrorKind,
	/**  Technical detail. */
	detail: string,
};

/**  Sent to the UI when something failed unexpectedly (a caught panic). */
export type AppErrorEvent = {
	/**  Technical summary for the log; the UI shows its own friendly text. */
	detail: string,
};

/**  Facts about an open document. */
export type DocInfo = {
	/**  Number of pages. */
	pageCount: number,
	/**  The Info dictionary's Title, if any. */
	title: string | null,
	/**  The Info dictionary's Author, if any. */
	author: string | null,
	/**  True when the file is encrypted (with or without a user password). */
	isEncrypted: boolean,
	/**  True when the document has an AcroForm. */
	hasForms: boolean,
	/**  PDF version, e.g. "1.7". */
	pdfVersion: string,
};

/**  An open document as the UI sees it. */
export type DocSummary = {
	/**  Engine document id; used in commands and tile URLs. */
	id: number,
	/**  Full path of the file. */
	path: string,
	/**  File name for tabs and titles. */
	fileName: string,
	/**  Facts about the document. */
	info: DocInfo,
	/**  Display size of every page, in points. */
	pageSizes: PageSize[],
	/**  Current revision (part of every tile URL). */
	revision: number,
};

/**  A stable, serializable error code for the UI (which picks the user-facing message). */
export type EngineErrorKind = 
/**  See [`EngineError::LibraryLoad`]. */
"libraryLoad" | 
/**  See [`EngineError::FileNotFound`]. */
"fileNotFound" | 
/**  See [`EngineError::Io`]. */
"io" | 
/**  See [`EngineError::PasswordRequired`]. */
"passwordRequired" | 
/**  See [`EngineError::WrongPassword`]. */
"wrongPassword" | 
/**  See [`EngineError::Malformed`]. */
"malformed" | 
/**  See [`EngineError::UnsupportedSecurity`]. */
"unsupportedSecurity" | 
/**  See [`EngineError::UnknownDocument`]. */
"unknownDocument" | 
/**  See [`EngineError::PageOutOfRange`]. */
"pageOutOfRange" | 
/**  See [`EngineError::InvalidRequest`]. */
"invalidRequest" | 
/**  See [`EngineError::Render`]. */
"render" | 
/**  See [`EngineError::Cancelled`]. */
"cancelled" | 
/**  See [`EngineError::WorkerStopped`]. */
"workerStopped" | 
/**  See [`EngineError::Internal`]. */
"internal";

/**  An outline (bookmark) entry. */
export type OutlineItem = {
	/**  Entry title. */
	title: string,
	/**  Target page, if the entry points at one in this document. */
	page: number | null,
	/**  Nested entries. */
	children: OutlineItem[],
};

/**  A page's display size in PDF points (1/72 inch), with the page's /Rotate already applied. */
export type PageSize = {
	/**  Width as displayed. */
	widthPt: number | null,
	/**  Height as displayed. */
	heightPt: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

