// Generated by tauri-specta. Do not edit; run `pnpm gen:ipc`.
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Opens the PDF at `path` and returns what the UI needs to show it. */
	openDocument: (path: string) => typedError<DocSummary, AppError>(__TAURI_INVOKE("open_document", { path })),
	/**  Closes a document and drops its cached tiles. */
	closeDocument: (docId: number) => typedError<null, AppError>(__TAURI_INVOKE("close_document", { docId })),
};

/* Types */
/**
 *  An error sent to the UI. The UI picks the user-facing message from `kind`; `detail` is technical
 *  and only for logs and bug reports.
 */
export type AppError = {
	/**  What went wrong. */
	kind: EngineErrorKind,
	/**  Technical detail. */
	detail: string,
};

/**  Facts about an open document. */
export type DocInfo = {
	/**  Number of pages. */
	pageCount: number,
	/**  The Info dictionary's Title, if any. */
	title: string | null,
	/**  The Info dictionary's Author, if any. */
	author: string | null,
	/**  True when the file is encrypted (with or without a user password). */
	isEncrypted: boolean,
	/**  True when the document has an AcroForm. */
	hasForms: boolean,
	/**  PDF version, e.g. "1.7". */
	pdfVersion: string,
};

/**  An open document as the UI sees it. */
export type DocSummary = {
	/**  Engine document id; used in commands and tile URLs. */
	id: number,
	/**  Full path of the file. */
	path: string,
	/**  File name for tabs and titles. */
	fileName: string,
	/**  Facts about the document. */
	info: DocInfo,
	/**  Display size of every page, in points. */
	pageSizes: PageSize[],
	/**  Current revision (part of every tile URL). */
	revision: number,
};

/**  A stable, serializable error code for the UI (which picks the user-facing message). */
export type EngineErrorKind = 
/**  See [`EngineError::LibraryLoad`]. */
"libraryLoad" | 
/**  See [`EngineError::FileNotFound`]. */
"fileNotFound" | 
/**  See [`EngineError::Io`]. */
"io" | 
/**  See [`EngineError::PasswordRequired`]. */
"passwordRequired" | 
/**  See [`EngineError::WrongPassword`]. */
"wrongPassword" | 
/**  See [`EngineError::Malformed`]. */
"malformed" | 
/**  See [`EngineError::UnsupportedSecurity`]. */
"unsupportedSecurity" | 
/**  See [`EngineError::UnknownDocument`]. */
"unknownDocument" | 
/**  See [`EngineError::PageOutOfRange`]. */
"pageOutOfRange" | 
/**  See [`EngineError::InvalidRequest`]. */
"invalidRequest" | 
/**  See [`EngineError::Render`]. */
"render" | 
/**  See [`EngineError::WorkerStopped`]. */
"workerStopped" | 
/**  See [`EngineError::Internal`]. */
"internal";

/**  A page's display size in PDF points (1/72 inch), with the page's /Rotate already applied. */
export type PageSize = {
	/**  Width as displayed. */
	widthPt: number | null,
	/**  Height as displayed. */
	heightPt: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

