[package]
name = "lumora-render"
description = "Tile math, tile cache and image encoding for Lumora PDF"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
